import { promises as fsPromises } from 'node:fs';
import { relative, resolve } from 'node:path';
import ts from 'typescript';

interface SymbolMember {
    name: string;
    kind: string;
    line: number;
}

interface SymbolEntry {
    name: string;
    kind: string;
    exported: boolean;
    line: number;
    members?: SymbolMember[];
}

interface ReExportEntry {
    kind: 're-export';
    source: string;
    exportedName: string;
    line: number;
}

interface FileEntry {
    path: string;
    symbols: SymbolEntry[];
    reExports: ReExportEntry[];
}

const ROOT = process.cwd();
const SOURCE_DIRS = ['src', 'scripts'];
const OUTPUT_PATH = resolve(ROOT, 'CODEMAP.md');
const HEADER = `# CODEMAP

Generated by \`npm run codemap\`.

The JSON block below is the machine-readable symbol index for coding agents.
`;

function isExported(node: ts.Node): boolean {
    return (ts.getCombinedModifierFlags(node as ts.Declaration) & ts.ModifierFlags.Export) !== 0;
}

function getLine(sourceFile: ts.SourceFile, node: ts.Node): number {
    return sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile)).line + 1;
}

function collectClassMembers(sourceFile: ts.SourceFile, classDeclaration: ts.ClassDeclaration): SymbolMember[] {
    return classDeclaration.members
        .map((member): SymbolMember | undefined => {
            if (ts.isConstructorDeclaration(member)) {
                return { name: 'constructor', kind: 'constructor', line: getLine(sourceFile, member) };
            }

            if (
                (ts.isMethodDeclaration(member) ||
                    ts.isPropertyDeclaration(member) ||
                    ts.isGetAccessorDeclaration(member) ||
                    ts.isSetAccessorDeclaration(member)) &&
                member.name
            ) {
                const name = member.name.getText(sourceFile);
                const kind = ts.isMethodDeclaration(member)
                    ? 'method'
                    : ts.isPropertyDeclaration(member)
                      ? 'property'
                      : ts.isGetAccessorDeclaration(member)
                        ? 'getter'
                        : 'setter';
                return { name, kind, line: getLine(sourceFile, member) };
            }

            return undefined;
        })
        .filter((member): member is SymbolMember => member !== undefined);
}

function collectSymbols(sourceFile: ts.SourceFile): FileEntry {
    const fileEntry: FileEntry = {
        path: relative(ROOT, sourceFile.fileName).replace(/\\/g, '/'),
        symbols: [],
        reExports: [],
    };

    for (const statement of sourceFile.statements) {
        if (ts.isFunctionDeclaration(statement) && statement.name) {
            fileEntry.symbols.push({
                name: statement.name.text,
                kind: 'function',
                exported: isExported(statement),
                line: getLine(sourceFile, statement),
            });
            continue;
        }

        if (ts.isClassDeclaration(statement) && statement.name) {
            fileEntry.symbols.push({
                name: statement.name.text,
                kind: 'class',
                exported: isExported(statement),
                line: getLine(sourceFile, statement),
                members: collectClassMembers(sourceFile, statement),
            });
            continue;
        }

        if (ts.isInterfaceDeclaration(statement)) {
            fileEntry.symbols.push({
                name: statement.name.text,
                kind: 'interface',
                exported: isExported(statement),
                line: getLine(sourceFile, statement),
            });
            continue;
        }

        if (ts.isTypeAliasDeclaration(statement)) {
            fileEntry.symbols.push({
                name: statement.name.text,
                kind: 'type',
                exported: isExported(statement),
                line: getLine(sourceFile, statement),
            });
            continue;
        }

        if (ts.isEnumDeclaration(statement)) {
            fileEntry.symbols.push({
                name: statement.name.text,
                kind: 'enum',
                exported: isExported(statement),
                line: getLine(sourceFile, statement),
            });
            continue;
        }

        if (ts.isVariableStatement(statement)) {
            for (const declaration of statement.declarationList.declarations) {
                if (ts.isIdentifier(declaration.name)) {
                    fileEntry.symbols.push({
                        name: declaration.name.text,
                        kind: 'variable',
                        exported: isExported(statement),
                        line: getLine(sourceFile, declaration),
                    });
                }
            }
            continue;
        }

        if (ts.isExportDeclaration(statement) && statement.moduleSpecifier) {
            const source = statement.moduleSpecifier.getText(sourceFile).slice(1, -1);
            if (statement.exportClause && ts.isNamedExports(statement.exportClause)) {
                for (const element of statement.exportClause.elements) {
                    fileEntry.reExports.push({
                        kind: 're-export',
                        source,
                        exportedName: element.name.text,
                        line: getLine(sourceFile, element),
                    });
                }
            } else {
                fileEntry.reExports.push({
                    kind: 're-export',
                    source,
                    exportedName: '*',
                    line: getLine(sourceFile, statement),
                });
            }
        }
    }

    return fileEntry;
}

async function collectSourceFiles(dir: string): Promise<string[]> {
    const entries = await fsPromises.readdir(dir, { withFileTypes: true });
    const files = await Promise.all(
        entries.map(async (entry): Promise<string[]> => {
            const fullPath = resolve(dir, entry.name);
            if (entry.isDirectory()) {
                return await collectSourceFiles(fullPath);
            }

            if (entry.isFile() && (entry.name.endsWith('.ts') || entry.name.endsWith('.d.ts'))) {
                return [fullPath];
            }

            return [];
        }),
    );

    return files.flat();
}

async function generateCodemap(): Promise<void> {
    const files = (
        await Promise.all(
            SOURCE_DIRS.map(async (dir): Promise<string[]> => {
                const absoluteDir = resolve(ROOT, dir);
                try {
                    return await collectSourceFiles(absoluteDir);
                } catch {
                    return [];
                }
            }),
        )
    )
        .flat()
        .sort((a, b) => a.localeCompare(b));

    const fileEntries = files.map((filePath) =>
        collectSymbols(ts.createSourceFile(filePath, ts.sys.readFile(filePath) ?? '', ts.ScriptTarget.Latest, true)),
    );
    const codemap = {
        generatedAt: new Date().toISOString(),
        root: relative(ROOT, ROOT) || '.',
        entrypoints: ['src/index.ts', 'src/cli.ts'],
        files: fileEntries,
    };

    const markdown = `${HEADER}
\`\`\`json
${JSON.stringify(codemap, null, 2)}
\`\`\`
`;

    await fsPromises.writeFile(OUTPUT_PATH, markdown, 'utf8');
}

void generateCodemap();
